name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write    # Add this line for permissions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   # Updated to v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '22'
          
      - name: Install dependencies
        run: |
          npm install
          
      - name: Build
        run: |
          npm run build
          ls -la build    # Debug: check build output
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4  # Updated to v4
        with:
          branch: gh-pages
          folder: build
          clean: true     # Add this to clean up old files

      - name: Check deployment
        run: |
          echo "Checking deployment..."
          git branch -a
